config/routes.rb
Rails.application.routes.draw do

  resources :business_ratings
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :businesses do
    resources :products
  end
  resources :tags
  resources :categories, only: [:index, :show]
  resources :users, only: [:show]
  root to: 'businesses#search'
  resources :business_rating, only: [:create, :update, :delete]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_creator, only: [:edit, :destroy]


  def search
  end

  def index
    @results = Business.search(params[:search])
  end

  def new
    @business = Business.new
    @business.build_business_rating
  end

  def edit
    @business = current_business
  end

  def show
    @business = current_business
  end

  def create

    # binding.pry
    @business = current_user.businesses.new(business_params)
    @business_rating = @business.business_rating
    @business.create_category_from_name unless business_params[:new_category_name].blank?
    respond_to do |format|
      if @business.valid?
        @business.save
        format.html { redirect_to business_path(@business), notice: "New business added." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @business = current_business
    @business_rating = BusinessRating.find_by_id(@business.business_rating_id)
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @business = current_business
    @user = current_user
    @business.destroy!
    render '/users/show', :notice => "Your business has been deleted"
  end

  private

  def current_business
    Business.find_by_id(params[:id])
  end

  def require_creator
    unless current_user.id == current_business.user_id
      flash[:error] = "You cannot make changes to a business you did not create"
      redirect_to user_path
    end
  end

  def business_params
    params.require(:business).permit(
      :name,
      :full_street_address,
      :website,
      :phone,
      :image,
      :user_id,
      :category_id,
      :new_category_name,
      :business_rating_attributes => [:rating]
    )
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_form.html.erb
<%= form_errors_for business %>

<%= form_for business do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, required: true %><br>

  <%= f.label :website %>
  <%= f.text_field :website %><br>

  <%= f.label :phone %>
  <%= f.text_field :phone %><br>

  <%= f.label :full_street_address %>
  <%= f.text_field :full_street_address %><br>


  Select a category:<br />
    <%= f.collection_radio_buttons :category_id, Category.all, :id, :name %><br />
  or add a new category:
    <%= f.text_field :new_category_name %>
    <br />

    <%= f.fields_for :business_rating, business.business_rating do |b| %>
        Business Rating
      <% 1.upto(5) do |i| %>
        <%= b.radio_button :rating, i, required: true %>
        <%= b.label :rating, i, :value => i %>
      <% end %>
    <% end %><br />


  <%= f.submit %>

<% end %>

app/views/businesses/_business_info.html.erb
  <h1><%= link_to business.name, business_path(business) %></h1>
  Category: <%= link_to business.category.name, category_path(business.category) unless business.category == nil %><br />
  Website: <%= link_to business.website %><br />
  Address: <%= business.full_street_address %><br />
  Phone: <%= business.phone %><br />
  Rating: <%= business.business_rating.rating unless business.business_rating == nil %>
  <br />

app/views/businesses/edit.html.erb
<h1>Edit <%= @business.name %></h1><br />

<%= render partial: "business_form", locals: {business: @business} %>

app/views/businesses/index.html.erb
<h2>Businesses</h2>

<% if @results.empty? %>
  Looks like we couldn't find any businesses that match your search.
<% else %>
  Here are your results:
  <ul>

    <% @results.each do |business| %>
      <li><%= render partial: "business_info", locals: {business: business} %> </li>
    <% end %>
  </ul>
<% end %>

app/views/businesses/new.html.erb
<h1>Add a New Business</h1>

<%= render partial: "business_form", locals: {business: @business} %>

app/views/businesses/search.html.erb
<h1>Find a Business</h1>

<%= form_tag businesses_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

View businesses by <%= link_to "category", categories_path %>

<h2>Recently added businesses</h2>
  <ul><% Business.recent.each do |biz| %>
    <li><%= link_to biz.name, biz %><% if biz.business_rating != nil %> - Rating: <%= biz.business_rating.rating %><% end %></li>
  <% end %></ul>

app/views/businesses/show.html.erb
<%= render partial: "businesses/business_info", locals: {business: @business} %>

<% if current_user && @business.user_id == current_user.id %>
  <%= link_to "Edit your business", edit_business_path(@business) %><br />
  <%= link_to "Delete your business", business_path(@business), :confirm => "Are you sure?", :method => :delete %><br />
  <%= link_to "Add a product", new_business_product_path(@business) %><br />
<% end %>

<ul><% @business.products.each do |product| %>
  <li><%= link_to product.name, business_product_path(@business, product) %></li>
<% end %></ul>