config/routes.rb
Rails.application.routes.draw do

  resources :business_ratings
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :businesses do
    resources :products
  end
  resources :tags
  resources :categories, only: [:index, :show]
  resources :users, only: [:show]
  root to: 'businesses#search'
  resources :business_rating, only: [:create, :update, :delete]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  mount_uploader :image, ImageUploader
  has_many :businesses

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(name: data['name'],
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<!-- # User info
# Edit Profile button
# If businesses - List of associated businesses
# If no businesses - Looks like you have no businesses message
# Add a new business link -->

<%= @user.email %><br />

<%= link_to "Edit your username/password", edit_user_registration_path %><br /><br />

<%= link_to "Add a business", new_business_path %><br />

<h2>Businesses you've added</h2>

<% if @user.businesses.any? %>
  <% @user.businesses.each do |business| %>
    <%= render partial: "businesses/business_info", locals: {business: business} %>
  <% end %>
<% else %>
  Looks like you haven't added any businesses yet.
<% end %><br />