config/routes.rb
Rails.application.routes.draw do

  resources :business_ratings
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :businesses do
    resources :products
  end
  resources :tags
  resources :categories, only: [:index, :show]
  resources :users, only: [:show]
  root to: 'businesses#search'
  resources :business_rating, only: [:create, :update, :delete]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :products_tags
  has_many :tags, through: :products_tags
  attr_accessor :new_tag_name
  has_many :businesses_products
  has_many :businesses, through: :businesses_products
  mount_uploader :image, ImageUploader
  validates :name, presence: true

  def create_tag_from_name
    new_tag = Tag.find_or_create_by(name: new_tag_name)
    self.tags << new_tag
  end

  def businesses_products_attributes=(businesses_products_attributes)
    businesses_products_attributes.values.each do |attribute|
        self.save
        self.businesses_products.build(attribute)
    end
  end

  #product.rating model

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_creator, only: [:edit, :destroy]


  def show
    @product = current_product
    @business = current_business
    @business_product = BusinessesProduct.find_by_product_id_and_business_id(@product.id, @business.id)
  end

  def index
  end

  def new
    @business = current_business
    @product = @business.products.new
    @businesses_products = @product.businesses_products.build
  end

  def create
    @business = current_business
    @product = @business.products.build(product_params)
    @product.businesses_products.last.business_id = @business.id
    respond_to do |format|
      if @product
        @product.create_tag_from_name unless product_params[:new_tag_name].blank?
        @product.save
        format.html { redirect_to business_path(@business), notice: "New product added." }
      else
        @product.errors.messages
        format.html { render :new }
      end
    end
  end

  def edit
    @product = current_product
    @business = current_business
  end

  def update
    @product = current_product
    @business = current_business
    respond_to do |format|
      if @product.valid?
        @tag = Tag.find_or_create_by(name: params[:product][:new_tag_name])
        @product.tags << @tag
        @product.save
        format.html { redirect_to business_product_path(@business, @product), notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product = current_product
    @business = current_business
    @product.destroy!
    render '/businesses/show', :notice => "Your product has been deleted"
  end

  private

  def current_product
    Product.find_by_id(params[:id])
  end

  def current_business
    Business.find_by_id(params[:business_id])
  end

  def require_creator
    unless current_user.id == current_business.user_id
      flash[:error] = "You cannot make changes to a business you did not create"
      redirect_to user_path
    end
  end

  def product_params
    params.require(:product).permit(
      :name,
      :new_tag_name,
      :business_id,
      :tag_ids => [],
      :businesses_products_attributes => [:product_rating]
    )
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products_add_tag.html.erb
<%= form_for([business, product]) do |f| %>

<%= form_errors_for product %>


    Add tag:<br />
        <%= f.text_field :new_tag_name %>
      <br />

    <%= f.submit %>

  <% end %>

app/views/products/_products_form.html.erb
<%= form_errors_for product %>

<%= form_for([business, product]) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true %><br>

    <%= f.fields_for :businesses_products, @businesses_products do |b| %>
      <!-- <%= b.hidden_field :business_id, value: business.id %> -->
        Product Rating
      <% 1.upto(5) do |i| %>
        <%= b.radio_button :product_rating, i, required: true %>
        <%= b.label :product_rating, i, :value => i %>
      <% end %>
    <% end %><br />

    <!-- add image? -->

    Add Tags:<br />
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br />
        <%= f.text_field :new_tag_name %>
      <br />


    <%= f.submit %>

  <% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1><br />

<%= render partial: "products_form", locals: {product: @product, business: @business} %>

app/views/products/new.html.erb
<h1>Add a New Product to <%= @business.name %></h1><br />

<%= render partial: "products_form", locals: {product: @product, business: @business} %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<h2>Rating: <%= @business_product.product_rating unless @business_product.nil? %></h2>

<!-- product.image -->

<%= product_tag_links(@product) %>

<% if current_user && @business.user_id == current_user.id %>
  <%= render partial: "products_add_tag", locals: {product: @product, business: @business} %>

  <%= link_to "Delete product", business_product_path, :confirm => "Are you sure?", :method => :delete %><br />
  <%= link_to "Edit product", edit_business_product_path(@business, @product) %>
<% end %>